### ISSUE TITLE
Mentor Reviews

### ISSUE THREAD

**Issue by Puriney** [Puriney/mxnet-gsoc-yunyan-application#7]
**Proposal**
Use the [latest version of repo](https://github.com/Puriney/mxnet-gsoc-yunyan-application/tree/d64c3de2cab5c53af824d55e8e476ff33d7b6a68) to be reviewed by mentors. 

**Notes**
- Melange link is deprecated by Google.
- Mentioning bioinformatics following Yuan's suggestion.

**Possible ways to  Comment**
Mentor could use 'Blame' view to track lines of proposal and comment.
Mentor could modify directly on markdown file.
Mentor could write comments in this issue.

**Misc**
Student proposal submission format = Draft (Google docs) + Final (PDF). Google docs are for comments from many sides, e.g. Google, R, etc. Therefore I could add figures into my proposal (thx Qiang's reminder).

**Comment by terrytangyuan** [comment]
Could you close this?
